safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: https://drl-dql.github.io/

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Yours Truly
    # url:  http://example.com/
    company:
        name: drl-dql
        url:  https://drl-dql.github.io/

# fork_url: https://github.com/shower/shower
progress: true
line_numbers: true
